### ISSUE TITLE
Multiple checkboxes

### ISSUE THREAD

**Issue by souldreamer** [Sawtaytoes/OneForm#12]
There's a use-case for multiple checkboxes (using both `isMultipleElement` and `isCheckboxElement`): [see an example here that it's a valid use-case](https://primefaces.org/primereact/showcase/#/checkbox) (taken from the component library I'm using). The resulting effect is somewhat like a multi-select, but with individual checkboxes (I've actually used such a construct a few times in past projects)

Pretty much this would boil down to:
```html
<Field isCheckboxElement isMultipleElement><Checkbox name="languagesSpoken" value="en" /></Field>
<Field isCheckboxElement isMultipleElement><Checkbox name="languagesSpoken" value="ro" /></Field>
<Field isCheckboxElement isMultipleElement><Checkbox name="languagesSpoken" value="pt" /></Field>
```

I've encountered 2 issues with implementing this use-case, both in `useField.js`'s return statement:
1. `value`: if a value isn't set in the default form values for this field, it will actually overwrite the values in the child checkboxes with `[]`, so changing the expression to something like:
```typescript
{ value: isMultipleElement && value === '' && (inputValue == null || inputValue === '') ? [] : inputValue || value }
```
2. `isChecked`: the conditions don't work for checkbox+multiple. I suggest using:
```typescript
{
isChecked: isCheckboxElement
  ? (isMultipleElement
      ? value?.includes(inputValue)
      : Boolean(value))
  : value === inputValue
      ? value
      : false
}
```

I've looked through the stories and seen the `MultiPicker` one, but tbh that's a bit convoluted when it could be easily fixed to "just work" and look more like one would implement radio buttons.

**Comment by Sawtaytoes** [comment]
The actual issue is that you're not supposed to pass `isCheckboxElement` and `isMultipleElement` at the same time. If you remove `isMultipleElement`, the multi-checkbox input works fine.

`isMultipleElement` is for multi-select for when you put the `multiple` attribute on a `<select>`. The only other place you'd use `multiple` is on `<input type="file" />`.

I originally needed a way to check if someone was using a checkbox because the logic in `useField` is pretty different. I was trying to infer it from the event (which I could), but I couldn't infer it in `Field` from the wrapped element.

Then I remembered multi-select was a thing and worked on that, but I added another boolean.

---

The correct fix is to convert these booleans into a finite state machine:
```js
const fieldTypes = {
  checkbox: 'checkbox',
  multiSelect: 'multiSelect',
  standard: 'standard',
}
```

Then I'd expect someone to pass in a single string instead of a single boolean.

This is a breaking change that needs a deprecation warning. Another helpful fix is using TypeScript types to restrict it to either boolean, but not both.

This change would need to happen in both `Field` and `useField` since many projects (like the one I have at work) will most-likely be creating their own `Field` components either directly through `useField` or with `translateProps`.

It's my fault for setting a bad standard in the first place, but at least, we don't have to hack-fix it either :).

**Comment by Sawtaytoes** [comment]
The actual issue is that you're not supposed to pass `isCheckboxElement` and `isMultipleElement` at the same time. If you remove `isMultipleElement`, the multi-checkbox input works fine.

## HTML `multiple` attribute
I intended `isMultipleElement` to only be used for `<select multiple>` and `<input type="file" />`. That's why it defaults to `[]`. It's actually the intended behavior based on the way input events also return arrays for those field types.

## `isMultipleElement`
`isMultipleElement` expects there to be a single parent element with multiple child elements that OneForm doesn't control. `Field` only wraps the parent element and doesn't know what's in there.

The `MultiPicker` example you pointed out is the same issue. It controls `children` and OneForm has no control over the `input`s inside.

### Prior Art
I've actually run into the same issue at work where a parent element is looping `children` and adding its own `onChange` and `value`. OneForm doesn't have control over those children even if I wrap them in `Field`.

In the same component, checkboxes can be radio buttons when it's single-select mode. In that case, passing no booleans makes it work as-expected. It only works because the picker component is handling its own internal state.

## `Subfield`
What you're wanting are `Subfield` and `useSubfield`.

I used them to wrap individual checkboxes and `options` for multi-select in the past, but I eventually found a way to do it all in `useField` and remove the need for `Subfield` altogether.

The files have been sitting there waiting for a use case. To update these components, `Subfield` would need `translateProps` function (more like `translateProp` 😆) similar to `Field`.

The `FieldContext.Provider` wrapping `children` in `Field` is what `Subfield` uses. Thing is, this context isn't using observables like everything else mainly because it was an experiment. For a real version of `Subfield`, we'll want `getValue`, `setValue`, and `subscribeToValue` passed to `FieldContext` rather than `value`.

I added a story using `Subfield`: edf0126a09a25575a0caa6b8b34c335ca3e4a899.

## Other Thoughts
I like how your solution "just works" because you can wrap each checkbox in `Field`; although, most situations like this, OneForm wouldn't have control over `children`; specifically in the case where you'd be using `isMultipleElement`.

`Subfield` was designed to solve your particular problem, but it still requires having a parent `Field` element and isn't as simple to implement not to mention it adds more code and probably isn't how people would assume this works.

Having to only rely on `Field` instead of `Subfield` is a better option.

## My Thoughts
_**NOTE:** These are my original thoughts before reading your post._

I'm thinking the correct fix is to convert these booleans into a finite state machine:
```js
const fieldTypes = {
  checkbox: 'checkbox',
  multiSelect: 'multiSelect',
  standard: 'standard',
}
```

Then I'd expect someone to pass in a single string instead of a single boolean.

This is a breaking change that needs a deprecation warning. Another helpful fix is using TypeScript types to restrict it to either boolean, but not both.

This change would need to happen in both `Field` and `useField` since many projects (like the one I have at work) will most-likely be creating their own `Field` components either directly through `useField` or with `translateProps`.

It's my fault for setting a bad standard in the first place, but at least, we don't have to hack-fix it in `useField` either :).

## Comparison
| `Field` | `Subfield` |
| --- | --- |
| One component to worry about. | Still requires a `Field` parent wrapper, but `Subfield` component makes your intent clear. The issue is either passing `name` to `Field` or putting it on a `div`. |
| Less things to worry about when creating custom `Field` components with `useField`. | Using the native `Field` element is fine. No need to use `FieldContext` when making custom `Field` components. |
| Requires code changes. | Already part of `OneForm`. |
| Requires no API changes. | Requires some way of restricting using both `isCheckboxElement` and `isMultipleElement` or simply changing them into a finite state machine. |
| Muddies up `Field` logic in a way that makes it harder to understand and might break in some edge cases. | Extra logic to worry about in `Field` along with yet another context consumer. This would definitely add some unnecessary bundle bloat. |

## Your thoughts?
After seeing these side-by-side, I'm leaning on "let's add it to `Field`".

What do you think?

**Comment by souldreamer** [comment]
`Radio groups` and `checkbox groups` are the same UX-wise as `select`s and `select multiple`s. So I really think that the way you use OneForm with them should be the same between radio groups and checkbox groups (and the added `isMultipleElement` from radio groups to checkbox groups would mirror the added one from `select` to `select multiple`).

I think for this particular use case it's the most obvious and natural way to use it. (It's kind of like why checked/indeterminate isn't a single value, but two different ones). 

I'm really not sure about `Subfield` to be honest. It seems redundant (and extraneous code). A `Field` with a `isCheckbox` and `isMultiple` and a `translateProps` to set `selected: isChecked` would do just as well without the extra context and such. Though in that case `isCheckbox` would be weird naming 😁.

**Comment by Sawtaytoes** [comment]
I'm cool with the changes in #14, and I'll eventually remove `Subfield` and `useSubfield`. They were only experimental, and it's great to finally get rid of them for `Field`-only solution.

I also agree that `selected` probably shouldn't be a default prop because it's only useful for `<select multiple>`, and that one works natively with a single `Field` wrapper anyway.
